social_networks:
  facebook:
    text: Facebook
    profile: 'https://www.facebook.com/BarnRemovalServices/'
    profile_order: '0'
    profile_enable: 1
    api_url: 'https://www.facebook.com/sharer.php?u=[current-page:url]&title=[current-page:title]'
    share_order: '0'
    share_enable: 1
    icon_class: fa-facebook
  twitter:
    text: Twitter
    profile: 'link to your profile page'
    profile_order: '1'
    profile_enable: 0
    api_url: 'https://twitter.com/intent/tweet?url=[current-page:url]&status=[current-page:title]+[current-page:url]'
    share_order: '1'
    share_enable: 1
    icon_class: fa-twitter
  linkedin:
    text: LinkedIn
    profile: 'link to your profile page'
    profile_order: '2'
    profile_enable: 0
    api_url: 'http://www.linkedin.com/shareArticle?mini=true&url=[current-page:url]&title=[current-page:title]&source=[current-page:url]'
    share_order: '2'
    share_enable: 1
    icon_class: fa-linkedin
  googleplus:
    text: Google-Plus
    profile: 'link to your profile page'
    profile_order: '3'
    profile_enable: 0
    api_url: 'https://plus.google.com/share?url=[current-page:url]'
    share_order: '3'
    share_enable: 1
    icon_class: fa-google-plus
  pinterest:
    text: Pinterest
    profile: 'link to your profile page'
    profile_order: '4'
    profile_enable: 0
    api_url: 'https://www.pinterest.com/pin/create/button/?url=[current-page:url]&description=[current-page:title]'
    share_order: '4'
    share_enable: 1
    icon_class: fa-pinterest
  behance:
    text: Behance
    profile: 'link to your profile page'
    profile_order: '5'
    profile_enable: 0
    api_url: ''
    share_order: '5'
    share_enable: 0
    icon_class: fa-behance
  dribbble:
    text: Dribbble
    profile: 'link to your profile page'
    profile_order: '6'
    profile_enable: 0
    api_url: ''
    share_order: '6'
    share_enable: 0
    icon_class: fa-dribbble
  youtube:
    text: YouTube
    profile: 'https://www.youtube.com/channel/UCClMfsa4r7NUS8DxIpg7YDg'
    profile_order: '7'
    profile_enable: 1
    api_url: ''
    share_order: '7'
    share_enable: 0
    icon_class: fa-youtube
  email:
    text: E-Mail
    profile: '[site:url]/contact/'
    profile_order: '10'
    profile_enable: 1
    api_url: 'mailto:?subject=[current-page:title]&body=You''ve gotta check out this site [current-page:url]'
    share_order: '10'
    share_enable: 1
    icon_class: fa-envelope-o
display_settings:
  link_buttons:
    class: soc-round
  share_buttons:
    class: soc-round
_core:
  default_config_hash: 90grncpevh5XL1MNbCMn_-us0_qB_IAG-7AV5FL2HGk
