<?php
/**
* @file
* Code for the Socializer module.
*/

/**
 * Implements hook_theme().
 */
 function socializer_theme($existing, $type, $theme, $path) {
   return array(
     'social_network_links' => array(
       'variables' => array(
         'title' => NULL,
         'description' => NULL,
         'elements' => NULL,
         'buttons' => NULL,
       ),
     ),
     'social_network_share' => array(
       'variables' => array(
         'title' => NULL,
         'description' => NULL,
         'elements' => NULL,
         'buttons' => NULL,
       ),
       //'render element' => 'elements',
       //'template' => 'block--social_network_share',
       //'base hook' => 'block'
     ),
   );
 }

?>
